#!/bin/bash

urls=(
"https://raw.githubusercontent.com/TheAlgorithms/C/master/sorting/bubble_sort.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/sorting/insertion_sort.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/sorting/selection_sort.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/search/binary_search.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/search/linear_search.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/maths/gcd.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/maths/lcm.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/maths/factorial.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/maths/fibonacci.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/data_structures/linked_list/linked_list.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/data_structures/stack/stack_array.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/data_structures/queue/queue_array.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/data_structures/tree/binary_search_tree.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/sorting/quick_sort.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/sorting/merge_sort.c"
"https://raw.githubusercontent.com/kirbs-/hash-table-c/master/hash_table.c"
"https://raw.githubusercontent.com/angrave/SystemProgramming/master/intro/dynamic_memory/simple_malloc.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/strings/reverse_string.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/strings/palindrome.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/strings/strlen.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/strings/strstr.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/strings/count_words.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/maths/prime.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/maths/sieve_of_eratosthenes.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/matrix/matrix_multiplication.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/matrix/determinant_of_matrix.c"
"https://raw.githubusercontent.com/angrave/SystemProgramming/master/files/file_read_write.c"
"https://raw.githubusercontent.com/angrave/SystemProgramming/master/pointers/pointer_basics.c"
"https://raw.githubusercontent.com/angrave/SystemProgramming/master/pointers/pointer_arithmetic.c"
"https://raw.githubusercontent.com/angrave/SystemProgramming/master/intro/args/print_args.c"
"https://raw.githubusercontent.com/SamyPesse/How-to-Make-a-Computer-Operating-System/master/code/shell/shell.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/strings/to_upper_case.c"
"https://raw.githubusercontent.com/TheAlgorithms/C/master/strings/atoi.c"
"https://raw.githubusercontent.com/fenbf/Simple-C-Calculator/master/calculator.c"
"https://raw.githubusercontent.com/changkun/cbook/master/01-basic/calendar.c"
"https://raw.githubusercontent.com/rho28/snake-in-c/master/snake.c"
)

for url in "${urls[@]}"; do
    wget "$url"
done
